map:
  width: 256
  height: 256
  grid_size: 3
  d_sample_hw:
  - 32
  - 32
  save_path:
  - E:/code/v3/version3.6/sim/map_data/grid_map0.npy
  - E:/code/v3/version3.6/sim/map_data/d_spl_map0.npy
agents:
  num: 2
  dT:
  - 0.02
  - 0.02
  id:
  - 6
  - 7
  theta:
  - - 0.83342175887101
    - -0.7738704659359297
  - - 0.08228801347018866
    - -0.8735602243516556
  pos:
  - - -24.0
    - 264.0
  - - 120.0
    - 192.0
  side:
  - 0
  - 0
  com_tensor:
  - - - 0
      - 0
      - 0
    - - 1
      - 0
      - 0
  - - - 1
      - 0
      - 0
    - - 0
      - 0
      - 0
  profiles:
  - water
  - water
target_distance:
  '6':
  - -1.0
  - 1.2246467991473532e-16
  '7':
  - 1.0
  - 0.0
formation_structure:
  6-7:
  - 10.0
  - -10.0
  7-6:
  - -10.0
  - 10.0
