default:
  v_max: 133.41
  r_turn_min: 24.76
  s_max: 10000
  sense_field: 278.48
  sense_angle_deg: 39.11
  sense_variance: 0.13
  attack_range: 194
  cannon_w_max_deg: 1138.22
  launch_delay: 12
  num_per_launch: 1
  attk_radius: 15.28
  attk_variance: 0.1
  cannon_capacity: 10
  smoke_capacity: 5
  reflective_surface: 0.89
  exposed_area: 7.07
  decision_delay: 4
  task_preference: 1
  task_assignment: 1
  weapon_assignment: 1
  connect_dist: 104
water:
  v_max: 109.04
  r_turn_min: 23.65
  s_max: 10000
  sense_field: 341.66
  sense_angle_deg: 40.06
  sense_variance: 0.29
  attack_range: 184
  cannon_w_max_deg: 832.62
  launch_delay: 8
  num_per_launch: 1
  attk_radius: 19.23
  attk_variance: 0.23
  cannon_capacity: 9
  smoke_capacity: 5
  reflective_surface: 1.1
  exposed_area: 7.07
  decision_delay: 3
  task_preference: 1
  task_assignment: 1
  weapon_assignment: 0
  connect_dist: 98
land:
  v_max: 132.75
  r_turn_min: 23.92
  s_max: 10000
  sense_field: 305.5
  sense_angle_deg: 38.33
  sense_variance: 0.12
  attack_range: 185
  cannon_w_max_deg: 954.1
  launch_delay: 13
  num_per_launch: 1
  attk_radius: 15.88
  attk_variance: 0.25
  cannon_capacity: 10
  smoke_capacity: 5
  reflective_surface: 0.91
  exposed_area: 7.07
  decision_delay: 2
  task_preference: 4
  task_assignment: 0
  weapon_assignment: 0
  connect_dist: 109
