default:
  v_max: 133.09
  r_turn_min: 22.74
  s_max: 10000
  sense_field: 285.05
  sense_angle_deg: 40.26
  sense_variance: 0.18
  attack_range: 185
  cannon_w_max_deg: 862.76
  launch_delay: 12
  num_per_launch: 1
  attk_radius: 17.02
  attk_variance: 0.25
  cannon_capacity: 8
  smoke_capacity: 5
  reflective_surface: 1.19
  exposed_area: 7.07
  decision_delay: 3
  task_preference: 3
  task_assignment: 0
  weapon_assignment: 0
  connect_dist: 91
